### PR TITLE
Add content about the API to the beginning of each vignette.

### PR DESCRIPTION
**Pull request by deflaux**

### CODE REVIEW

**Comment by siddharthab** [comment]
Let me know when you are ready to merge. Don't worry about Travis if things render fine.

**Comment by pgrosu** [comment]
Yeah, I'm also seeing the same title rendered twice:

http://bioconductor.org/packages/devel/bioc/vignettes/GoogleGenomics/inst/doc/VariantAnnotation-comparison-test.html

http://bioconductor.org/packages/devel/bioc/vignettes/GoogleGenomics/inst/doc/PlottingAlignments.html

Below is are a couple of screenshots:

variant_title_2

plot_title_2

~p

**Comment by pgrosu** [comment]
At the top of some pages, I see some R source code getting rendered regarding getting the API key from the environment variable `GOOGLE_API_KEY`.  Below is an example:

api_key

**Comment by pgrosu** [comment]
Are you guys requiring R 3.1.3 to work with this package?  I'm getting the following error:

```R
> library(GoogleGenomics)
Loading required package: GenomicAlignments
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following object is masked _by_ ‘.GlobalEnv’:

    get

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall,
    clusterEvalQ, clusterExport, clusterMap,
    parApply, parCapply, parLapply, parLapplyLB,
    parRapply, parSapply, parSapplyLB

The following object is masked from ‘package:stats’:

    xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame,
    as.vector, cbind, colnames, do.call,
    duplicated, eval, evalq, Filter, Find, get,
    intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind,
    Reduce, rep.int, rownames, sapply, setdiff,
    sort, table, tapply, union, unique, unlist,
    unsplit

Loading required package: S4Vectors
Loading required package: stats4
Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: Biostrings
Loading required package: XVector
Loading required package: Rsamtools
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘checkmate’
In addition: Warning message:
package ‘GenomeInfoDb’ was built under R version 3.1.3 
Error: package ‘GenomicAlignments’ could not be loaded
> 
```

**Comment by deflaux** [comment]
@siddharthab I think this is good to go for now.  The issue with two titles might still be there, but let's figure that out later.

@pgrosu I'm not sure about the R version issue you are running into.  This particular PR did not change the dependencies of the package in any way.  

Regarding the API KEY blurb, its intentional that its in the vignette but not displayed in the rendered result.  It should help if people are trying to run the vignette manually.

**Comment by siddharthab** [comment]
@pgrosu The version warning you are seeing is because you upgraded R but did not upgrade the packages. Some of the packages you have on your system were built for R 3.1.3 and might not work well. The warning will go away when you upgrade all packages. This is completely unrelated to GoogleGenomics.

**Comment by pgrosu** [comment]
@deflaux Ah, thanks for the vignette clarification - that makes sense :)  Regarding the double-title it probably is because of the following:

*Lines 41-43:*
```HTML
<div id="header">
  <h1 class="title">Reproducing Variant Annotation Results</h1>
</div>
```
which gets rendered as:
```HTML
<div id="header">
  <h1 style="margin-top: 0px;" class="title">
    Reproducing Variant Annotation Results
  </h1>
</div>
```
*Line 74*: 
```HTML
<h1>Reproducing Variant Annotation Results</h1>
```
which is under the following `div` tag, that starts on line 74:
```HTML
<div id="reproducing-variant-annotation-results" class="section level1">
```

@siddharthab Hmm...maybe, but I'm pretty sure I checked the R version on my home computer and it said 3.1.2 and then I did the standard `biocLite()...update all/some/none packages (a/s/n)` and chose `a` for all, and still got the same thing.  I'm not running the `devel` version.  I'll try it again tonight when I get home - or on the cluster later in the day - and let you know how it goes.

thx,
~p

**Comment by ttriche** [comment]
@pgrosu -- try pulling either a release or devel Docker image from BioC and
run it in there, it will be rather more revealing.  I don't even bother
reporting errors in my personal BioC setup any more unless I can replicate
them in one of the above Dockers


Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by pgrosu** [comment]
Hi Tim,

I agree, but I am trying to play the naïve user/biologist who is just following the instructions that are written.  I should not need to download a Docker image, since I assume that since the package is part of BioConductor - with the assumption of being thoroughly tested - which I tried to help by performing this on almost all the Google Genomics client PRs before they are merged.  Some users they have their own intricate collection of R scripts, and would be hesitant to download a new R version and update scripts or move things around.  In any case, for example in the following file that is part of this PR:

https://github.com/Bioconductor/GoogleGenomics/blob/c6f1cc21a1b5f98f3413a4f896455ac6d9419ab1/inst/doc/PlottingAlignments.md

the `sessionInfo()` says that it was tested with `## R version 3.1.1 (2014-07-10)` and thus I have something similar (i.e. R 3.1.2).  I then did more tests, and noticed the following warning that I need a higher version of R than what the `Provenance` section lists:

```R
The downloaded binary packages are in
        C:\Users\Me\AppData\Local\Temp\RtmpoP9Avs\downloaded_packages
Warning message:
package ‘GoogleGenomics’ is not available (for R version 3.1.2) 
```
Of course I switched to that R version, since I have a collection of R versions installed and I test these releases based solely on what is written in the documentation files of these releases.  Some biologists I worked with in the past are not computer experts, but are fantastic at following protocols and instructions.  It's sort of the testing lens I polished for myself over the years, after having given many data analysis training sessions to biologists that spanned a spectrum of computer/programming expertise.  Thus these instructions have to be precise and complete for all users, as the GA4GH and GoogleGenomics releases are geared to make this analysis simple and intuitive.  

Hope you have a great weekend,
Paul

**Comment by pgrosu** [comment]
Sorry just noticed [the file](https://github.com/deflaux/GoogleGenomics/blob/50442943088f48e24fb66462e8fbe5d227977921/vignettes/PlottingAlignments.Rmd) is updated in the `Provenance` section with just having the `sessionInfo()` command, without any output information regarding the version details used to generate the results.  So that section probably would need to be updated to list or the minimum required version for users to be at, including some plots (and outputs), in order for people to have some idea of what things should look like.

**Comment by ttriche** [comment]
@pgrosu these are good points. are you going to be in Seattle?  Because I
already have numerous slides' worth of bitching to do about other aspects
of user-facing changes.  At some point it's unbecoming to bite the hand
that feeds me so often.  But if somebody ELSE ranted at developer day,
well, I certainly couldn't be held responsible for THAT ;-)

BioC is one of the best run (perhaps the best run) open bioinformatics
projects in existence and is largely responsible for R being what it is.
Your remarks get right to the heart of some thorny issues when integrating
pay-as-you-go cloud providers with open, reproducible, tested project
infrastructures.




Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by pgrosu** [comment]
@ttriche  I would love to be in Seattle, but unfortunately I'm swamped with two papers due before the end of the summer.  I share the same sentiments for BioC, since it is what attracted me to the community almost ten years ago and still does.  I understand your frusturations and think your presentation would benefit others, but ideally it should project the theme as helpful recommendations that others might benefit from.  It took me 16 years to learn how to test projects properly - both in academia and in industry - and this is not something that can be taught overnight without being practiced.  Actually failure was my best teacher :)  The most helpful presentations in this domain were ones that gently introduced me to the reasoning behind all the concepts of testing - that also included examples - and how they all integrated together.  I tried to write my posts on GA4GH the same way - some which took me sometimes a week to do - but will be there forever so people can keep coming back to them over years.

I think one other element that helps here is if it is practiced as a team on real projects.  So for instance, we all come together and polish the end product of GoogleGenomics until it works just right.  Sure there will be grumbling along the way, but in the end we get a fairly good product.  If we think a PR is not ready, we throw in a test to proves that something needs to be fixed to fit the standard we are accustomed to.  I'm not sure how many tests the nice folks at Google have - besides the ones in the PRs - but just in case for more than a year I collected a few tests I cherrypick from to run on most of the PRs.  Ideally we have release notes with every version, so that we know what tests would need to updated.  It's understandable that not all of us have access to the backend of the API to determine what might fail a test, but over time we get fairly good coverage.  Ideally yes, we have a standard collection of tests that everything goes through - similarly how [hellbender](https://github.com/broadinstitute/hellbender) gets looked at by different members of the Broad and Google teams on a variety of tests - but until then we are those test teams and suggest what might be helpful in the roadmap.  There is a ton of low-hanging fruit in this project so the potential is huge here over the next few years.

~p

**Comment by ttriche** [comment]
@pgrosu my fussing is orthogonal to that of testing (ok, maybe not really,
since build tests for downstream packages perhaps ought to have caught some
of the fallout) but the short version is, in BioC the standard operating
procedure is to wait 2 release cycles before defunct()ing a function or
package.  Deprecation throws a warning, and the idea is that users have a
solid year to fix any downstream effects.  However, the recent migration of
the SummarizedExperiment class (which is foundational, and was featured in
a recent Nature Methods paper as it existed just a few months ago) has not
followed these conventions, and has resulted in a great deal of fallout
that could have been avoided by simply following the traditional
deprecation cycle.

Testing has not historically been my forte (it's only recently that it sunk
in just how much unnecessary maintenance work can be avoided with proper
testing) so I'm simply not in a position to preach to others about
testing.  It does seem to be wise to canonicalize the build/test
environment, as BioC is starting to do with release and devel containers,
so that bug reports and build failure reports at least have a reproducible
context.  There's something to be said for detective work, but "it's an
efficient use of time" is probably not that something.

Best,

--t


Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by pgrosu** [comment]
@ttriche  I totally agree that the development lifecycle and testing process for BioC would benefit in being revisited and tightened.  I'm really happy to hear you also share in the ideas behind the benefits of testing - it took me many years to see it - and we can all work as a team with BioC community to gradually adopt these ideas, though I'm sure some already know them.  

Since seeing the full spectrum of testing could be overwhelming for some, to make it a more gentle adoption, the simplest is to use a test-driven development [TDD] approach, which would be like starting with writing the complete vignette before doing any coding - including all examples and expected outputs - of how every function and class must operate before actually coding it.  Usually when I construct programs, I follow a consistent design recipe where I first start with the test cases - including all edge cases - of how I expect the outputs to be based on the inputs, while using only the function names. This takes up the majority of the time. Then I add the function contracts to the functions (i.e. the defined arguments/parameters) in terms of inputs and outputs based on the tests. I implement them first on the tests, and then add them with expanded definitions to the defined functions. Then these define the commented definition for each function and its types - the interpretation was previously defined via the test cases.  It is only the last 10% of this process that I actually code, which becomes a very mechanical process, since the plan is already written for me by me - having gone through the process of analyzing the complete problem and breaking it into its succinct components. I feel that if the community follows something along these lines of planning out any implementation and its coding portion, then it would be seldom that any surprises would creep up.  All tests of course would travel along with each appropriate package, and in case of R/BioC they can be part of the `Examples` section for the help page of the function.  Any cross-project tests can also be included as necessary.  If more complex testing is required, then that can be be visited when appropriate.

To expand, the above TDD approach can be augmented with a behavior-driven development [BDD] approach, by utilizing a standard such as the [Gherkin language](http://behat.readthedocs.org/en/v2.5/guides/1.gherkin.html):

```
Feature: Retrieving assays in a SummarizedExperiment
  Scenario: Retrieving reads using assay() function
    Given a SummarizedExperiment
    When the assay() function is applied on SummarizedExperiment
    Then the assays within the SummarizedExperiment are returned
```

Then once these descriptive and unit-test type approaches are applied and pass, then all the other complex types of testing (i.e. integration, regression, smoke, etc.) would be performed before the package is released.

So, yes I definitely agree that the development lifecycle and testing process for BioC would benefit in being revisited and tightened, and thus your presentation would be _*essential*_ to the community.

Best,
~p

**Comment by pgrosu** [comment]
Regarding ensuring that packages follow the deprecation cycle, these would need to have an automatic trigger that would halt the package based on an addition deprecation file, that would be submitted by the larger community. This file lists all the functions to be deprecated.  If during the followup release cycle some functions are not deprecated, then it would generate an additional file, with the list of the functions which should have been deprecated, along with an email-alert to the owner of the package.  If on the second release cycle it still has not, then the package is halted until it is fixed.  If the package is deemed critical to many other ones, then it would freeze the release until the package is fixed.  This might be too "industry-like" and overwhelming to a friendly community, but I'm sure via discussions a compromise can be reached which would integrate with a public ticket/svn system, where ideally people can be allowed to jump in an approved manner and fix things for high-impact packages.

**Comment by seandavi** [comment]
@pgrosu and @ttriche: Just a suggestion, but perhaps it is worth having some of this more general discussion on bioc-devel where it is a bit more open.

**Pull request merged**
